---
repos:

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.17.1
      hooks:
          - id: check-github-workflows


    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
            language_version: python3 # Should be a command that runs python3.6+

    - repo: https://github.com/PyCQA/flake8
      rev: 5.0.4
      hooks:
          - id: flake8
            args: [--count, --show-source, --statistics]
